# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
filter = { only_tables = ["pt_account", "pt_account_details"] }
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "C:\\Users\\Trung\\Downloads\\rust-rocket\\migrations"
